spring:
  profiles:
    active: dev
  application:
    name: Chat

  thymeleaf:
    cache: false

  data:
    mongodb:
      uri: "mongodb://localhost:27017/chat_db"
      database: chat_db

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 1004
  servlet:
    context-path: /chat
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8



