server:
#  port: 0
  port: 1012

spring:
  application:
    name: customer-service


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/insahi?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  sql:
    init:
      encoding: UTF-8
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: none
#
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  header: Authorization
  secret: aGVhdmVzIHNwcmluZyBzZWN1cml0eSBqd3QgZXhhbWE=
  #  token-validity-in-second: 86400000 #60*60*24*1000
  token-validity-in-second: 86400 #60*60*24*1000


#jwt:
#  header: Authorization
#  secret: aGVhdmVzIHNwcmluZyBzZWN1cml0eSBqd3QgZXhhbWE=
##  token-validity-in-second: 86400000 #60*60*24*1000
#  token-validity-in-second: 86400 #60*60*24*1000

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#
#  instance:
##    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30