apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments/FileApp.yaml
  - deployments/Kafka.yaml
  - deployments/Redis.yaml
  - deployments/Service.yaml
  - deployments/Volume.yaml
  - config/kafka-broker-config.yaml
  - config/redis-config.yaml
  - config/common-config.yaml
