apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PASSWORD
          volumeMounts:
            - mountPath: /data
              name: redis-storage
          command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc       # 퍼시스턴스를 위한 PVC 사용
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  REDIS_PASSWORD: "your-redis-password"  # Redis 비밀번호 설정
