apiVersion: apps/v1
kind: Deployment
metadata:
  name: appr
  namespace: insahi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insahi-appr
  template:
    metadata:
      labels:
        app: insahi-appr
    spec:
      containers:
        - name: appr
          image: daul0519/appr-service:9239009
          ports:
            - containerPort: 1005
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_KEY


---


apiVersion: v1
kind: Service
metadata:
  name: appr-service
  namespace: insahi

spec:
  type: ClusterIP
  selector:
    app: insahi-appr

  ports:
    - port: 1005
      targetPort: 1005
