apiVersion: apps/v1
kind: Deployment
metadata:
  name: atdsal
  namespace: insahi
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 20
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: insahi-atdsal
  template:
    metadata:
      labels:
        app: insahi-atdsal
    spec:
      containers:
        - name: atdsal
          image: daul0519/atdsal-service:8888294
          ports:
            - containerPort: 1000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"



---


apiVersion: v1
kind: Service
metadata:
  name: atdsal-service
  namespace: insahi

spec:
  type: ClusterIP
  selector:
    app: insahi-atdsal

  ports:
    - port: 1000
      targetPort: 1000
