apiVersion: apps/v1
kind: Deployment
metadata:
  name: atdsal
  namespace: insahi
spec:
  replicas: 1
  selector:
    matchLabels:
      project: insahi
  template:
    metadata:
      labels:
        project: insahi
    spec:
      containers:
        - name: appr
          image: daul0519/atdsal-service:1.3
          ports:
            - containerPort: 1000



---


apiVersion: v1
kind: Service
metadata:
  name: atdsal-service
  namespace: insahi

spec:
  type: LoadBalancer
  selector:
    project: insahi

  ports:
    - port: 1000
      targetPort: 1000
