apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm
  namespace: insahi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insahi-hrm
  template:
    metadata:
      labels:
        app: insahi-hrm
    spec:
      containers:
        - name: hrm
          image: daul0519/hrm-service:4a847b9
          ports:
            - containerPort: 1010
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod



---

apiVersion: v1
kind: Service
metadata:
  name: hrm-service
  namespace: insahi

spec:
  type: ClusterIP
  selector:
    app: insahi-hrm

  ports:
    - port: 1010
      targetPort: 1010
