apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm
  namespace: insahi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insahi-hrm
  template:
    metadata:
      labels:
        app: insahi-hrm
    spec:
      containers:
        - name: hrm
          image: daul0519/hrm-service:4.5
          ports:
            - containerPort: 1010
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_KEY



---

apiVersion: v1
kind: Service
metadata:
  name: hrm-service
  namespace: insahi

spec:
  type: ClusterIP
  selector:
    app: insahi-hrm

  ports:
    - port: 1010
      targetPort: 1010
