url:
  service:
    att: "http://127.0.0.1:1000"


server:
  port: 1010

spring:
  profiles:
    active: dev   # default 환경: dev
  security:
    user:
      name: admin
      password: 1234
  application:
    name: employee

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/insahi?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  sql:
    init:
      encoding: UTF-8
      mode: always

  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gyusang123@gmail.com
    password: uqld cwav slzs gjyu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

file:
  upload-dir: C:/fullstack7/work/final-project/InsaHi/HumanResourceManagement/uploads/profile/

jwt:
  header: Authorization
  secret: 4Hirx6BNM+kTbhOxA4cHCUz/BF0B0tokIgTRs2d5ORn3zF8fPAESoo/jXcUiBnWYoZWrxgunF3l3gvGCUi6JGQ==
  token-validity-in-second: 86400000 #60*60*24*1000
  #token-validity-in-second: 86400 #60*60*24*1000


#jwt:
#  header: Authorization
#  secret: aGVhdmVzIHNwcmluZyBzZWN1cml0eSBqd3QgZXhhbWE=
##  token-validity-in-second: 86400000 #60*60*24*1000
#  token-validity-in-second: 86400 #60*60*24*1000

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
