att:
  service:
    url: http://127.0.0.1:1000

server:
  port: 1010

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/insahi?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      use_sql_comments: true
      ejb:
        persistenceUnitName: userData
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: insahi

  sql:
    init:
      encoding: UTF-8
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: gyusang123@gmail.com
    password: uqld cwav slzs gjyu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  header: Authorization
  secret: 4Hirx6BNM+kTbhOxA4cHCUz/BF0B0tokIgTRs2d5ORn3zF8fPAESoo/jXcUiBnWYoZWrxgunF3l3gvGCUi6JGQ==
  token-validity-in-second: 86400000 # 60*60*24*1000

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor: trace
