server:
  #  port: 0
  port: 1010

spring:
  security:
    user:
      name: admin
      password: 1234
  application:
    name: hrm

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://insahi.cremqog6y49m.ap-northeast-2.rds.amazonaws.com:3306/insahi
    username: mytest
    password: playdata

  sql:
    init:
      encoding: UTF-8
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gyusang123@gmail.com
    password: uqld cwav slzs gjyu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

file:
  upload-dir: /uploads/insahi/profile/
  access-url: http://127.0.0.1:1010/uploads/profile/
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka


#  redis:
#    host: localhost            # Redis 서버 호스트
#    port: 6379                 # Redis 서버 포트
#    password:                  # 비밀번호 (필요한 경우)
#    timeout: 10000             # 연결 타임아웃 (밀리초)
#    lettuce:
#      pool:
#        max-active: 10         # 최대 연결 수
#        max-idle: 5            # 최대 유휴 연결 수
#        min-idle: 1            # 최소 유휴 연결 수
#        max-wait: 10000        # 최대 대기 시간 (밀리초)

jwt:
  header: Authorization
  secret: 4Hirx6BNM+kTbhOxA4cHCUz/BF0B0tokIgTRs2d5ORn3zF8fPAESoo/jXcUiBnWYoZWrxgunF3l3gvGCUi6JGQ==
  token-validity-in-second: 86400000
  #token-validity-in-second: 86400 #60*60*24*1000
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static-region: ap-northeast-2
    s3:
      bucket: insahi
    stack:
      auto: false
#jwt:
#  header: Authorization
#  secret: aGVhdmVzIHNwcmluZyBzZWN1cml0eSBqd3QgZXhhbWE=
##  token-validity-in-second: 86400000 #60*60*24*1000
#  token-validity-in-second: 86400 #60*60*24*1000

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace


