feign:
  client:
    position:
      url: "${url.service.att}"

url:
  service:
    att: "http://localhost:1000"

server:
  port: 1010

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # SQL 쿼리를 콘솔에 출력
    packages-to-scan:
      - com.playdata.HumanResourceManagement
      - com.playdata.AttendanceSalary

    properties:
      hibernate:
        ejb:
          persistenceUnitName: userData
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        default_schema: insahi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/insahi?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  sql:
    init:
      encoding: UTF-8
      mode: always

jwt:
  header: Authorization  # JWT 헤더 설정
  secret: 4Hirx6BNM+kTbhOxA4cHCUz/BF0B0tokIgTRs2d5ORn3zF8fPAESoo/jXcUiBnWYoZWrxgunF3l3gvGCUi6JGQ==
  token-validity-in-second: 86400

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor: trace
