hrm:
  service:
    url: http://127.0.0.1:1010

approval:
  service:
    url: http://127.0.0.1:1005

server:
  port: 1000

spring:
  application:
    name: AttendanceSalary

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/insahi?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      # ddl-auto 설정: 자동 스키마 생성 및 수정 방지 권장
      ddl-auto: update  # 개발 환경에서만 사용, 프로덕션에서는 none 추천
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
